models/meeting.py
from typing import Optional
from datetime import datetime

from app import db


class Meeting(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    meeting_creator = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    max_bikers = db.Column(db.Integer, nullable=True, default=None) #  None if no limit
    area = db.Column(db.String(256), nullable=False)
    trail = db.Column(db.String(256), nullable=False)
    date_time = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(64), nullable=False)
    description = db.Column(db.Text)
    min_skill = db.Column(db.Integer, nullable=True, default=0)



participants = db.Table("participants",
    db.Column("user_id", db.Integer, db.ForeignKey("user.id")),
    db.Column("meet_id", db.Integer, db.ForeignKey("meeting.id"))
)

app/meeting/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import IntegerField, StringField, TextField, SelectField, SubmitField
from wtforms.fields.html5 import DateField, TimeField
# from wtforms.validators import 


class CreateMeetingForm(FlaskForm):
    num_of_bikers = IntegerField("Number of bikers")
    area = StringField("Area")
    trail = StringField("Trail")
    date = DateField("Date")
    time = TimeField("Starting time")
    title = StringField("Add a title")
    description = TextField("Add a description")
    min_skill = SelectField("Skill level required", choices=list(range(1, 6)))
    submit = SubmitField("Create your meeting!")

app/meeting/__init__.py
from flask import Blueprint

bp = Blueprint("meeting", __name__, url_prefix="/meeting")

from app.meeting import routes

app/meeting/routes.py
import json
from datetime import datetime
import json

from flask import redirect, render_template, url_for, request, jsonify
from flask_login import login_required, current_user

from app import db
from app.meeting import bp
from app.meeting.forms import CreateMeetingForm
from models.user import User
from models.meeting import Meeting
from models.bikes import Cities, Regions


@login_required
@bp.route("create-meeting", methods=["GET", "POST"])
def create_meeting():
    form = CreateMeetingForm()
    if form.validate_on_submit():
        meeting = Meeting(
            meeting_creator=current_user.id,
            max_bikers=form.num_of_bikers.data,
            area=form.area.data,
            trail=form.trail.data,
            date_time=datetime.fromisoformat(f"{form.date.data} {form.time.data}"),
            title=form.title.data,
            description=form.description.data,
            min_skill=form.min_skill.data
        )
        db.session.add(meeting)
        current_user.participations.append(meeting)
        db.session.commit()
        return redirect(url_for("main.profile"))

    context = {
        "title": "Create a meeting",
        "form": form
    }
    return render_template("meeting/create_meeting.html", **context)


@login_required
@bp.route("join-meeting")
def join_meeting():
    args  = request.args

    area  = args.get('area', None)
    date  = args.get('date', None)
    skill = args.get('skill', None)

    query = Meeting.query
    if area is not None:
        query = query.filter_by(area=area)
    
    if date is not None:
        query = query.filter(Meeting.date_time > datetime.fromisoformat(date))

    if skill is not None:
        query = query.filter(Meeting.min_skill <= skill)

    meetings = query.all()

    context = {
        "title": "Join a meeting",
        "meetings": meetings
    }
    return render_template("meeting/join_meeting.html", **context)


@bp.route("/join", methods=["POST"])
def join():
    meeting_id = int(json.loads(request.data)["meeting_id"])
    if meeting_id is None:
        return jsonify({"status": "failed"})
    meeting = Meeting.query.get(meeting_id)
    if meeting in current_user.participations:
        return jsonify({"status": "failed", "message": "You're already in the competition"})
    if current_user.skill_level >= meeting.min_skill:
        current_user.participations.append(Meeting.query.get(meeting_id))
        db.session.commit()
        print(meeting in current_user.participations)
        return jsonify({"status": "success"})
    return jsonify({"status": "failed", "message": f"You're skill level is lower than {meeting.min_skill}"})


@login_required
@bp.route("activities")
def activities():
    meetings = sorted(current_user.participations, key=lambda x: x.date_time, reverse=True)
    context = {
        "title": "Activities",
        "meetings": meetings,
        "now": datetime.utcnow()
    }
    return render_template("meeting/activities.html", **context)


@login_required
@bp.route("cancel-paricipition", methods=["POST"])
def cancel_participition():
    meeting_id = int(json.loads(request.data).get("meeting_id", None))
    if meeting_id is None:
        return jsonify(
            {"status": "failed", "message": "No meeting_id arg in request."}
        )
    elif Meeting.query.get(meeting_id) not in current_user.participations:
        return jsonify({
            "status": "failed",
            "message": f"You are not a participant of meeting {meeting_id}"
        })
    else:
        current_user.participations = list(filter(lambda meeting: meeting.id != meeting_id, current_user.participations))
        db.session.commit()
        return jsonify(
            {"status": "success", "message": "success"}
        )

    participations_count = len(current_user.participations)
    current_user.participations = list(filter(lambda x: x.id != meeting_id, current_user.participations))
    db.session.commit()
    if len(current_user.participations) == participations_count:
        return jsonify(
            {"status": "failed", "message": "You are not a participant in the meeting {meeting_id}"}
        )
    return jsonify({"status": "success"})

    
@login_required
@bp.route("bike-rent")
def bike_rent():
    cities = Cities.query.all()
    context = {
        "title": "Rent a bike",
        "cities": cities
    }
    return render_template("meeting/bike_rent.html", **context)


@login_required
@bp.route("get-shops", methods=["POST"])
def get_shops():
    data = json.loads(request.data)
    print(data["region"])
    region = Regions.query.filter_by(region=data["region"]).first()
    print("Region.shops: ", region.shops)
    shops = list()

    for shop in list(region.shops):
        shops.append({
            "name"  : shop.name,
            "url"   : shop.shop_url,
            "region": Regions.query.get(shop.region_id).region
        })

    print(shops)
    return jsonify({"status": "success", "shops": shops})

templates/meeting/activities.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block css_links %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/join.css') }}">
{% endblock %}

{% block content %}
<div class="container">
<div class="join__results results-card">
    {% for meeting in meetings %}
    <div class="join__card {% if now < meeting.date_time %} not-over {% endif %} ">
    <div class="join__desc">
        <span>Title: <span>{{ meeting.title }}</span></span>
        <span>When: <span>{{ meeting.date_time }}</span></span>
        <span>Where: <span>{{ meeting.area }}</span></span>
        <span>Skill level: <span>{{ meeting.min_skill }}</span></span>
        <!-- <span>Notes: <span>blablabla</span></span> -->
    </div>
    <div class="join__creator">
        <div class="join__creator-head">
            <div class="join__person">
                <span>{{ meeting.creator.username }}</span>
                <div class="join__img">
                    {% if meeting.creator.avatar %}
                        <img src="{{ url_for('static', filename=meeting.creator.avatar) }}" alt="" />
                    {% else %}
                        <img src="{{ url_for('static', filename='img/anon-user.png') }}" alt="" />
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="join__creator-body">
            <div class="join__details" id="{{ meeting.id }}">See details</div>
                <div class="join__join join__cancel" id="{{ meeting.id }}">Cancel</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}

{% block scripts %}
<script>
    const buttons = document.getElementsByClassName('join__join');
    
    for(let i = 0; i < buttons.length; i++) {

        let meetingId = buttons[i].id;
        buttons[i].addEventListener('click', () => {
            if (!buttons[i].classList.contains("inactive-btn")) {
                 fetch('{{ url_for("meeting.cancel_participition") }}', {
                     method: 'POST',
                     mode: 'cors',
                     body: JSON.stringify({ meeting_id: meetingId})
                 })
                 .then(data => data.json())
                 .then(data => {
                     if(data.status === 'success') {
                         buttons[i].classList.add('inactive-btn')
                         buttons[i].parentElement.parentElement.parentElement.style.display = 'none'
                     }
                     console.log(data)
                 })
            }
        })
    }


 </script>
 <script>
    let detail_btns = document.getElementsByClassName("join__details");
    for (let detail_btn of detail_btns) {
        detail_btn.onclick = () => {
            console.log(detail_btn.id)
            createModal(detail_btn.id)
        }
    }

    function createModal(meeting_id) {
        {% for meeting in meetings %}
        if (meeting_id == {{ meeting.id }}) {
            const modal = document.createElement('div');
            modal.innerHTML = `
            <div id="popup" class="sign-in__popup open">
                <div class="popup__body">
                    <div id='popup__content' class="pop__cont popup__content content__open">
                    <a class="popup__close">x</a>
                    <h2>{{meeting.title}}</h2>
                    {% if meeting.description %}
                        <p>{{meeting.description}}</p>
                    {% else %}
                        <p>No description.</p>
                    {% endif %}
                    <p>Creator: {{meeting.creator.username}}</p>
                    <p>Date: {{meeting.date_time.date()}}</p>
                    </div>
                </div>
                </div>
            `
            
            modal.addEventListener('click', () => {
                modal.classList.add('non')
            })
           
            document.body.appendChild(modal)
        }
        {% endfor %}

    }
</script>
 {% endblock %}

templates/meeting/bike_rent.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block css_links %}
<link rel="stylesheet" href="{{url_for('static', filename='css/bike.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

{% endblock %}

{% block content %}
    <div class="container">
        <div id="shop-search">
            <div id="city-search">

                <select class=" sel f_select" name="city" id="select-city">
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for city in cities %}
                    
                        <option value="{{ city.city }}">{{ city.city }}</option>
                    {% endfor %}
                </select>
            </div>
            <div id="region-search">

                <select class="sel s_select" name="region" id="select-region">
                    
                </select>
            </div>
            <div id="search-shops-btn">BUTTON</div>
        </div>
        <div id="shop__cards">

        </div>
    </div>
{% endblock %}


{% block scripts %}
<script>
    let selectCity = document.getElementById("select-city");
    let shopCards = document.getElementById('shop__cards');
    selectCity.onchange = () => {
        let city = selectCity.value;
        let regions;
        let selectRegion = document.getElementById("select-region");
        selectRegion.innerHTML = "";
        let option;
        {% for city in cities %} 
            if ("{{ city.city }}" === city) {
                {% for region in city.regions %}
                    option = document.createElement("option");
                    option.innerHTML = "{{region.region}}";
                    option.value = "{{region.region}}";
                    selectRegion.appendChild(option);
                {% endfor %}
            }
        {% endfor %}
        console.log(regions)
    }
</script>

<script>
    let button = document.getElementById("search-shops-btn");
    button.onclick = () => {
        const shops = document.createElement('div');
        shopCards.innerHTML = ''
        fetch("{{ url_for('meeting.get_shops') }}", {
            method: "POST",
            mode: "cors",
            body: JSON.stringify({
                region: document.getElementById("select-region").value
            })
        }).then(data => data.json())
            .then(data => {
                
                data.shops.map(shop => (
                    shops.innerHTML = `
                    <div class='shop__card'>
                        <p>Name: ${shop.name}</p>
                        <p>Region: ${shop.region}</p>
                        <p>URL: ${shop.url}</p>
                        </div>
                `
                ))
                
                console.log(data)
                shopCards.appendChild(shops)
            })
    }
</script>
<script>

</script>
{% endblock %}

templates/meeting/create_meeting.html
{% extends "base.html" %}


{% block title %} {{title}} {% endblock %}
{% block css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/meeting-form.css') }}">
  {% endblock %}

{% block content %}

<div class="container">
    <div class="meeting__title">
        <h3>Create a meeting</h3>
    </div>
    
    <form method="post" id="create-meeting-form">
        {{ form.hidden_tag() }}
        <div class="cmf__field">
            {{form.num_of_bikers.label}} 
            <div class="limit-btn">no limit</div>
            {{form.num_of_bikers(class_="select-css limit-int")}}

            {% for error in form.num_of_bikers.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.area.label}} 
            {{form.area}}
            {% for error in form.area.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.trail.label}} 
            {{form.trail}}
            {% for error in form.trail.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.date.label}} 
            {{form.date}}
            {% for error in form.date.errors %}
            <span style="color: red">{{error}}</span>
            {% endfor %}
            
        </div>
        <div class="cmf__field">
            {{form.time.label}} 
            {{form.time}}
            {% for error in form.time.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.title.label}} 
            {{form.title}}
            {% for error in form.title.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.description.label}} 
            {{form.description}}
            {% for errors in form.description.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{form.min_skill.label}} 
            {{form.min_skill}}
            {% for error in form.min_skill.errors %}
                <span style="color: red">{{error}}</span>
            {% endfor %}
        </div>
        <div class="cmf__field">
            {{ form.submit() }}
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/limit.js') }}"></script>
{% endblock %}

templates/meeting/join_meeting.html
{% extends "base.html" %}

{% block css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/join.css') }}">
{% endblock %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<div class="container">
    <div class="join__block">
        <div class="join__search-block">
            <div class="join__search">
                <span>Search for: </span>
                <input  type="text" class="first-input"  placeholder="Area" />
                <input type='date' class="second-input" placeholder="Date" />
          
                <select class="select-css" name="skill level" id="third-input">
                    <option disabled>Skill level</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
                <button class="join__btn">click</button>
            </div>
        </div>
        <div class="join__results results-card">
            {% for meeting in meetings %}
            <div class="join__card">
            <div class="join__desc">
                <span>Title: <span>{{ meeting.title }}</span></span>
                <span>When: <span>{{ meeting.date_time }}</span></span>
                <span>Where: <span>{{ meeting.area }}</span></span>
                <span>Skill level: <span>{{ meeting.min_skill }}</span></span>
                <!-- <span>Notes: <span>blablabla</span></span> -->
            </div>
            <div class="join__creator">
                <div class="join__creator-head">
                    <div class="join__person">
                        <span>{{ meeting.creator.username }}</span>
                        <div class="join__img">
                            {% if meeting.creator.avatar %}
                                <img src="{{ url_for('static', filename=meeting.creator.avatar) }}" alt="" />
                            {% else %}
                                <img src="{{ url_for('static', filename='img/anon-user.png') }}" alt="" />
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="join__creator-body">
                    <div class="join__details" id="{{ meeting.id }}">See details</div>
                    <div class="join__join {% if meeting in current_user.participations %} inactive-btn {% endif %}" id="{{ meeting.id }}">Join</div>
                    <!-- url_for("meeting.join") body={"meeting_id": id}-->
                        
                </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    const firstInput = document.querySelector('.first-input');
    const secondInput = document.querySelector('.second-input');
    const thirdInput = document.querySelector('#third-input');
    const btn = document.getElementsByClassName('join__btn')[0];
    
    let link = `{{ url_for('meeting.join_meeting') }}`;

    let args = []

    btn.addEventListener('click', () => {

        if(firstInput.value.trim() !== '') {
            args.push(`area=${firstInput.value.trim()}`)
        }
        if(secondInput.value.trim() !== '') { 

            args.push(`date=${secondInput.value.trim()}`)

        }  
        if(thirdInput.value.trim() !== '') { 

            args.push(`skill=${thirdInput.value.trim()}`)
        }   
        let args_string = '';
        if (args.length !== 0) {
            args_string = '?' + args.join('&');
        }
        console.log(link + args_string);
        args = [];
        firstInput.value = ''
        secondInput.value = ''
        thirdInput.value = '1'

        location.href = link + args_string;

    })
</script>

<script>
   const buttons = document.getElementsByClassName('join__join');

   for(let i = 0; i < buttons.length; i++) {
       let meetingId = buttons[i].id;
       buttons[i].addEventListener('click', () => {
           if (!buttons[i].classList.contains("inactive-btn")) {
                fetch('{{ url_for("meeting.join") }}', {
                    method: 'POST',
                    mode: 'cors',
                    body: JSON.stringify({ meeting_id: meetingId})
                })
                .then(data => data.json())
                .then(data => {
                    if(data.status === 'success') {
                        buttons[i].classList.add('inactive-btn')
                    } else if (data.status === "failed") {
                        //console.log(document.getElementById("flash-message"))
                        //document.getElementById("flash-message").innerHTML = data.message;
                        let div = document.createElement("div")
                        div.classList.add("alert")
                        div.innerHTML = `<span id="flash-message">${data.message}</span>`
                        document.getElementsByClassName("container-alert")[0].appendChild(div)
                        window.onclick = () => {
                            document.getElementsByClassName("container-alert")[0].innerHTML = "";
                            window.onclick = null;
                        }
                    }
                    console.log(data)
                })
           }
       })
       
   }
</script>
<script>
    let detail_btns = document.getElementsByClassName("join__details");
    for (let detail_btn of detail_btns) {
        detail_btn.onclick = () => {
            console.log(detail_btn.id)
            createModal(detail_btn.id)
        }
    }

    function createModal(meeting_id) {
        {% for meeting in meetings %}
        if (meeting_id == {{ meeting.id }}) {
            const modal = document.createElement('div');
            modal.innerHTML = `
            <div id="popup" class="sign-in__popup open">
                <div class="popup__body">
                    <div id='popup__content' class="pop__cont popup__content content__open">
                    <a class="popup__close">x</a>
                    <h2>{{meeting.title}}</h2>
                    {% if meeting.description %}
                        <p>{{meeting.description}}</p>
                    {% else %}
                        <p>No description.</p>
                    {% endif %}
                    <p>Creator: {{meeting.creator.username}}</p>
                    <p>Date: {{meeting.date_time.date()}}</p>
                    </div>
                </div>
                </div>
            `
            
            modal.addEventListener('click', () => {
                modal.classList.add('non')
            })
           
            document.body.appendChild(modal)
        }
        {% endfor %}

    }
</script>
<script>
    //  for(let i = 0; i < buttons.length; i++) {
    // buttons[i].addEventListener('click', () => {
    //     buttons[i].classList.toggle('inactive-btn')
    //     buttons[i].innerHTML = 'sdf'
    //     if(buttons[i].textContent == 'sdf') {
    //     buttons[i].innerHTML = 'Join'

    //     }
    // })

    //  }

    // const pop = document.createElement('div');
    // pop.innerHTML = `
    // <div id="popup" class="sign-in__popup">
    //   <div class="popup__body">
    //     <div class="popup__content">
    //       <a class="popup__close">x</a>
    //     </div>
    //   </div>
    // </div>`;
    // console.log(pop)

    // const cards = document.getElementsByClassName('join__results');
    // for(let i = 0; i < cards.length; i++) {
    //     cards[i].addEventListener('click', (e) => {
    //         if(e.target.className == 'join__details') {
    //             console.log('dick', e.target.parentElement.parentElement.previousElementSibling)
    //             const pop = document.createElement('div');
    // pop.innerHTML = `
    // <div id="popup" class="sign-in__popup">
    //   <div class="popup__body">
    //     <div class="popup__content">
    //       <a class="popup__close">x</a>
    //       <p>sdf</p>
    //     </div>
    //   </div>
    // </div>`;
    //         }
    //     })
    // }

</script>
{% endblock %}